include ../Makefile.config

INCL+=-I../include
MACFLAGS+=-i../include

SRCC=
SRCS=collision.s
OBJS=$(SRCC:.c=.o) $(SRCS:.s=.o)

DISTFILES=Makefile $(SRCC) $(SRCH) $(SRCS) 
INSTALLLIB=collision.o

include ../Makefile.template
