include ../Makefile.config

INCL+=-I../include

SRCC=a_sprite.c c_layer.c d_sprite.c iter_all.c iter_one.c 
SRCC+=n_sprite.c s_sprite.c so_layer.c 
SRCC+=m_layer.c h_layer.c s_layer.c
SRCS=
OBJS=$(SRCC:.c=.o) $(SRCS:.s=.o)

DISTFILES=Makefile $(SRCC) $(SRCS) $(SRCH)

INSTALLLIB=

include ../Makefile.template
