JAGPATH?=$(JAGTOOLS)
CROSSPATH?=$(M68KTOOLS)/m68k-aout

MADMAC=$(JAGPATH)/bin/mac
CC=$(CROSSPATH)/bin/gcc
AR=$(CROSSPATH)/bin/ar

#MACFLAGS=-fb -v
MACFLAGS=-fb 
CFLAGS=-mc68000 -Wall -fomit-frame-pointer -O2 -msoft-float 

DOXYGEN=doxygen

TARGET=$(HOME)/tmp/rmvlib
