MADMAC=$(JAGPATH)/bin/mac
CC=m68k-aout-gcc
AR=m68k-aout-ar

#MACFLAGS=-fb -v
MACFLAGS=-fb 

JLIBC=$(JAGPATH)/src/jlibc

INCL=-I$(JLIBC)/include
CFLAGS=-mcpu=68000 -Wall -fomit-frame-pointer -O2 -msoft-float $(INCL)

DOXYGEN=doxygen

TARGET=$(JAGPATH)/lib

