include ../Makefile.config

INCL+=-I../include

SRCC=
SRCS=render.s
OBJS=$(SRCC:.c=.o) $(SRCS:.s=.o)

DISTFILES=Makefile $(SRCC) $(SRCH) $(SRCS) render_def.s
INSTALLLIB=render.o

include ../Makefile.template
