include ../Makefile.config

INCL+=-I../include

SRCC=open_skunk_file.c
SRCS=skunk.s
OBJS=$(SRCC:.c=.o) $(SRCS:.s=.o)

DISTFILES=Makefile $(SRCC) $(SRCH) $(SRCS) 
INSTALLLIB=

include ../Makefile.template
