include ../Makefile.config

INCL+=-I../include

SRCC=open_console.c open_custom_console.c new_custom_console.c
SRCS=
OBJS=$(SRCC:.c=.o) $(SRCS:.s=.o)

DISTFILES=Makefile $(SRCC) $(SRCS) $(SRCH)
INSTALLLIB=

include ../Makefile.template
