include ../Makefile.config

INCL+=-I../include
MACFLAGS+=-i../include

SRCC=
SRCS=lz77.s
OBJS=$(SRCC:.c=.o) $(SRCS:.s=.o)

DISTFILES=Makefile $(SRCC) $(SRCH) $(SRCS)
INSTALLLIB=lz77.o

include ../Makefile.template
